// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Server")>]
[<assembly: AssemblyProductAttribute("Suave/Fable sample")>]
[<assembly: AssemblyDescriptionAttribute("Suave and Fable sample")>]
[<assembly: AssemblyVersionAttribute("0.1.5")>]
[<assembly: AssemblyFileVersionAttribute("0.1.5")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Server"
    let [<Literal>] AssemblyProduct = "Suave/Fable sample"
    let [<Literal>] AssemblyDescription = "Suave and Fable sample"
    let [<Literal>] AssemblyVersion = "0.1.5"
    let [<Literal>] AssemblyFileVersion = "0.1.5"
    let [<Literal>] AssemblyConfiguration = "Release"
