init:
  - git config --global core.autocrlf input
environment:
  nodejs_version: "6.0"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
os: Visual Studio 2015
before_build:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.1.{build}
