// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("msu.SmartMeterHome")>]
[<assembly: AssemblyProductAttribute("msu.SmartMeterHome")>]
[<assembly: AssemblyDescriptionAttribute("Ein Portal zur Abfrage der SmartMeter-Daten.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "msu.SmartMeterHome"
    let [<Literal>] AssemblyProduct = "msu.SmartMeterHome"
    let [<Literal>] AssemblyDescription = "Ein Portal zur Abfrage der SmartMeter-Daten."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
